# Dedicated services for Admin app
parameters:
  # All admin context listeners should be executed before the router listener, this way even if no symfony route is found they context are initialized
  # and can be used in admin legacy pages as well (router listener priority is 32)
  employee_listener_priority: 35
  language_listener_priority: 34
  default_listener_priority: 33

services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  # SECURITY
  prestashop.adapter.security.admin:
    class: "%AdapterSecurityAdminClass%"
    arguments:
      - "@prestashop.adapter.legacy.context"
      - "@security.token_storage"
      - "@prestashop.security.admin.provider"
      - "@security.helper"
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  prestashop.tokenized_url_listener:
    class: PrestaShopBundle\EventListener\TokenizedUrlsListener
    autowire: true
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  # Priority 40 to be called before the RouterListener (which has priority 32)
  prestashop.legacy_url_listener:
    class: PrestaShopBundle\EventListener\LegacyUrlListener
    arguments:
      - "@prestashop.bundle.routing.converter.legacy_url_converter"
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 40 }

  # Priority 30 to be called after the RouterListener
  prestashop.legacy_parameters_listener:
    class: PrestaShopBundle\EventListener\LegacyParametersListener
    arguments:
      - "@prestashop.bundle.routing.converter.legacy_parameters_converter"
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 30 }

  PrestaShopBundle\EventListener\AccessDeniedListener:
    autowire: true
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

  PrestaShopBundle\EventListener\AdminSecurityListener:
    autowire: true
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  prestashop.bundle.event_listener.back_url_redirect_response_listener:
    class: PrestaShopBundle\EventListener\BackUrlRedirectResponseListener
    arguments:
      - '@PrestaShop\PrestaShop\Core\Util\Url\BackUrlProvider'
      - "@prestashop.adapter.legacy.context"
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

  prestashop.user_locale.listener:
    class: PrestaShopBundle\EventListener\UserLocaleListener
    arguments:
      - "@prestashop.adapter.legacy.context"
      - "@prestashop.adapter.legacy.configuration"
      - "@prestashop.core.admin.lang.repository"
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 15 }

  # Context listeners

  # Employee context must have a higher priority because Shop and Language depend on it
  PrestaShopBundle\EventListener\Context\Admin\EmployeeContextListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: '%employee_listener_priority%' }

  # Language depends on Employee so its priority is lower, however it has higher priority than Currency and Country because they depend on Language
  PrestaShopBundle\EventListener\Context\Admin\LanguageContextListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: '%language_listener_priority%' }

  PrestaShopBundle\EventListener\Context\Admin\ShopContextListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: '%default_listener_priority%' }

  PrestaShopBundle\EventListener\Context\Admin\CurrencyContextListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: '%default_listener_priority%' }

  PrestaShopBundle\EventListener\Context\Admin\CountryContextListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: '%default_listener_priority%' }

  # This listener must run after the router listener since it's based on the request attributes that are defined by the router
  PrestaShopBundle\EventListener\Context\Admin\LegacyControllerContextListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  PrestaShopBundle\EventListener\Context\Admin\LegacyContextListener:
    arguments:
      $legacyBuilders: !tagged_iterator core.legacy_context_builder
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
