imports:
  - { resource: ../config_test.yml }
  - { resource: config.yml }

framework:
  router:
    resource: "%kernel.project_dir%/app/config/oauth-api/routing_test.yml"
    strict_requirements: ~
  profiler: { only_exceptions: false }
