admin_authorized_applications_index:
  path: /applications
  methods: [ GET ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\AuthorizationServer\ApplicationController::indexAction
    _legacy_controller: AdminAuthorizationServer

admin_authorized_applications_view:
  path: /applications/{applicationId}
  methods: [ GET ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\AuthorizationServer\ApplicationController::viewAction
    _legacy_controller: AdminAuthorizationServer
    categoryId: null
  requirements:
    applicationId: \d+

admin_authorized_applications_create:
  path: /applications/create
  methods: [ GET, POST, PATCH ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\AuthorizationServer\ApplicationController::createAction
    _legacy_controller: AdminAuthorizationServer

admin_authorized_applications_edit:
  path: /applications/{applicationId}/edit
  methods: [ GET, POST, PATCH ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\AuthorizationServer\ApplicationController::editAction
    _legacy_controller: AdminAuthorizationServer
  requirements:
    applicationId: \d+

admin_authorized_applications_delete:
  path: /applications/{applicationId}/delete
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\AuthorizationServer\ApplicationController::deleteAction
    _legacy_controller: AdminAuthorizationServer

admin_api_accesses_index:
  path: /api-accesses
  methods: [ GET ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\AuthorizationServer\ApiAccessController::indexAction
    _legacy_controller: AdminAuthorizationServer
    _legacy_link: AdminAuthorizationServer

admin_api_accesses_create:
  path: /api-accesses/create
  methods: [ GET, POST, PATCH ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\AuthorizationServer\ApiAccessController::createAction
    _legacy_controller: AdminAuthorizationServer

admin_api_accesses_edit:
  path: /api-accesses/{apiAccessId}/edit
  methods: [ GET, POST, PATCH ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\AuthorizationServer\ApiAccessController::editAction
    _legacy_controller: AdminAuthorizationServer

admin_api_accesses_delete:
  path: /api-accesses/{apiAccessId}/delete
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\AuthorizationServer\ApiAccessController::deleteAction
    _legacy_controller: AdminAuthorizationServer

admin_api_accesses_toggle_active:
  path: /api-accesses/{apiAccessId}/toggle-active
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Configure\AdvancedParameters\AuthorizationServer\ApiAccessController::toggleActiveAction
    _legacy_controller: AdminAuthorizationServer
