admin_login:
  path: /login
  methods: [ GET, POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\LoginController::loginAction'
    _legacy_controller: AdminLogin
    # _legacy_link: AdminLogin
