admin_login:
  path: /login
  methods: [ GET, POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\LoginController::loginAction'
    _legacy_controller: AdminLogin
    _legacy_link: AdminLogin

admin_logout:
  path: /logout
  methods: [ GET ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\LoginController::logoutAction'
    _legacy_controller: AdminLogin
    _legacy_link: AdminLogin:logout

admin_homepage:
  path: /
  condition: request.getMethod() == 'GET' and not request.query.has('controller')
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\LoginController::homepageAction'
