services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\ApiAccess\CommandHandler\AddApiAccessHandler:

  PrestaShop\PrestaShop\Adapter\ApiAccess\CommandHandler\EditApiAccessHandler:

  PrestaShop\PrestaShop\Adapter\ApiAccess\CommandHandler\DeleteApiAccessHandler:

  PrestaShop\PrestaShop\Adapter\ApiAccess\CommandHandler\GenerateSecretApiAccessHandler:

  PrestaShop\PrestaShop\Adapter\ApiAccess\QueryHandler\GetApiAccessForEditingHandler:

  prestashop.hasher:
    class: 'Symfony\Component\PasswordHasher\Hasher\NativePasswordHasher'

  PrestaShopBundle\Service\HashService:
    arguments:
      - '@prestashop.hasher'
