services:
  _defaults:
    public: false
    autowire: true

  PrestaShop\PrestaShop\Adapter\Attribute\CommandHandler\DeleteAttributeHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Attribute\CommandHandler\BulkDeleteAttributeHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Attribute\Repository\AttributeRepository:
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  PrestaShop\PrestaShop\Adapter\Attribute\CommandHandler\AddAttributeHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Attribute\CommandHandler\EditAttributeHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Attribute\QueryHandler\GetAttributeForEditingHandler:
    autoconfigure: true

  PrestaShop\PrestaShop\Adapter\Attribute\Validate\AttributeValidator:
